services:
    web-app:
      build:
        context: .
      ports:
        - "8088:8088"
      volumes:
        - ./service:/service
      command:
         sh -c  "python manage.py runserver 0.0.0.0:8088"