# Generated by Django 4.2 on 2024-06-26 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_group_students_group_price_groupstudents'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='estimator',
            new_name='teacher',
        ),
    ]
