# Generated by Django 5.0.6 on 2024-06-26 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_estimator_score_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_score', to='main.group'),
        ),
    ]
